[theme]
base = "light"
primaryColor = "#ffb162"
backgroundColor = "#eee9df"
secondaryBackgroundColor = "#ffffff"
textColor = "#1b2632"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
